---
include:
  - board: nice_nano_v2
    shield: settings_reset

  # ---- Keyball ----
  - board: nice_nano_v2
    shield: keyball61_left
    artifact-name: keyball_left

  - board: nice_nano_v2
    shield: keyball61_right
    artifact-name: keyball_right

